#!/bin/ksh 

########################################
# Preliminary data setup step
########################################
set -xa
export PS4='$SECONDS + ' 
date

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-hiresw}
export RUN=${RUN:-href}

export IOBUF_PARAMS='*:size=8M:count=8'

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################

## PDY not included here as pull data from PDYm1 as well

# export COMINhiresw=${COMINhiresw:-$(compath.py hiresw/prod/hiresw)}

# needed?
# export COMINpcpanl=${COMINpcpanl:-$(compath.py pcpanl/prod)}

export HOMEhref=${HOMEhref:-$NWROOT/href.${href_ver}}
export EXEChref=${EXEChref:-$HOMEhref/exec}
export PARMhref=${PARMhref:-$HOMEhref/parm}
export USHhref=${USHhref:-$HOMEhref/ush}
export FIXhref=${FIXhref:-$HOMEhref/fix}
export SCRIPTShref=${SCRIPTShref:-$HOMEhref/scripts}


########################################################### 
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT}/href_qpfeasfrac_${cyc}_${envir}.${pid}}
mkdir -p $DATA
rm -rf $DATA/*
cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-$COMROOT/logs/jlogfile}


####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

export cycle=${cycle:-t${cyc}z}


##################################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

###################################
# Set up the UTILITIES
###################################
msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

# setpdy.sh
# . PDY

echo have PDY as $PDY


##############################################
# Define running directory and COM directories
##############################################

if [ "$RUN_ENVIR" != nco ] ; then
  export COMOUT=${COMOUT:-${MYCOMROOT}/${NET}/${envir}/${RUN}.${PDY}_expv3}
else
  export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
fi

if [ ! -d $COMOUT ] ; then
 mkdir -p $COMOUT/ensprod
 mkdir -p $COMOUT/verf_g2g
fi

 
########################################################
# Execute the script.

if [ -e poe.qpf_6 ] 
then
rm poe.*
fi

echo "#! /bin/sh" > poe.qpf_24

hrs="24 27 30 33 36 39 42 45 48 51 54 57 60"
for fhr in $hrs
do
echo "#! /bin/sh" > poe.qpf_24_${fhr}
echo "cd ${DATA}; mkdir qpf_${fhr}_24; cd qpf_${fhr}_24 ; python ${HOMEhref}/scripts/make_easfracqpf_combo.py ${fhr} 24 >  qpf_combo_${dom}_${cyc}_24h_${fhr}.log" >> poe.qpf_24_${fhr}

chmod 775 poe.qpf_24_${fhr}
echo "./poe.qpf_24_${fhr} &" >> poe.qpf_24
done
echo "wait" >> poe.qpf_24
chmod 775 poe.qpf_24

echo "#! /bin/sh" > poe.qpf_6
hrs="06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60"
for fhr in $hrs
do

echo "#! /bin/sh" > poe.qpf_6_${fhr}
echo "cd ${DATA}; mkdir qpf_${fhr}_6; cd qpf_${fhr}_6 ; python ${HOMEhref}/scripts/make_easfracqpf_combo.py ${fhr} 6 > qpf_combo_${dom}_${cyc}_6h_${fhr}.log" >> poe.qpf_6_${fhr}

# echo "cd ${DATA}; mkdir snow_${fhr}_6; cd snow_${fhr}_6; python ${HOMEhref}/scripts/make_easfracsnow_combo.py ${fhr} 6 > snow_combo_${dom}_${cyc}_6h_${fhr}.log" >> poe.qpf_6

chmod 775 poe.qpf_6_${fhr}
echo "./poe.qpf_6_${fhr} &" >> poe.qpf_6
done

echo "wait" >> poe.qpf_6
chmod 775 poe.qpf_6

echo "#! /bin/sh" > poe.qpf_12
hrs="12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60"
for fhr in $hrs
do
echo "#! /bin/sh" > poe.qpf_12_${fhr}
echo "cd ${DATA}; mkdir qpf_${fhr}_12; cd qpf_${fhr}_12 ; python ${HOMEhref}/scripts/make_easfracqpf_combo.py ${fhr} 12 >  qpf_combo_${dom}_${cyc}_12h_${fhr}.log" >> poe.qpf_12_${fhr}
chmod 775 poe.qpf_12_${fhr}
echo "./poe.qpf_12_${fhr} &" >> poe.qpf_12
done
echo "wait" >> poe.qpf_12
chmod 775 poe.qpf_12


echo "#! /bin/sh" > poe.qpf_3
hrs="03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60"
for fhr in $hrs
do
echo "#! /bin/sh" > poe.qpf_3_${fhr}

echo "cd ${DATA}; mkdir qpf_${fhr}_3; cd qpf_${fhr}_3 ; python ${HOMEhref}/scripts/make_easfracqpf_combo.py ${fhr} 3  > qpf_combo_${dom}_${cyc}_3h_${fhr}.log" >> poe.qpf_3_${fhr}

# echo "cd ${DATA}; mkdir snow_${fhr}_3; cd snow_${fhr}_3; python ${HOMEhref}/scripts/make_easfracsnow_combo.py ${fhr} 3 > snow_combo_${dom}_${cyc}_3h_${fhr}.log" >> poe.qpf_3

chmod 775 poe.qpf_3_${fhr}
echo "./poe.qpf_3_${fhr} &" >> poe.qpf_3

done
echo "wait" >> poe.qpf_3
chmod 775 poe.qpf_3


echo "#! /bin/sh" > poe.qpf_1a
hrs="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24"
for fhr in $hrs
do
echo "#! /bin/sh" > poe.qpf_1_${fhr}

echo "cd ${DATA}; mkdir qpf_${fhr}_1; cd qpf_${fhr}_1 ; python ${HOMEhref}/scripts/make_easfracqpf_combo.py ${fhr} 1 > qpf_combo_${dom}_${cyc}_1h_${fhr}.log" >> poe.qpf_1_${fhr}

# echo "cd ${DATA}; mkdir snow_${fhr}_1; cd snow_${fhr}_1; python ${HOMEhref}/scripts/make_easfracsnow_combo.py ${fhr} 1 >  snow_combo_${dom}_${cyc}_1h_${fhr}.log" >> poe.qpf_1a
chmod 775 poe.qpf_1_${fhr}
echo "./poe.qpf_1_${fhr} &" >> poe.qpf_1a
done

echo "wait" >> poe.qpf_1a
chmod 775 poe.qpf_1a

#####

echo "#! /bin/sh" > poe.qpf_1b
hrs="25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60"
for fhr in $hrs
do
echo "#! /bin/sh" > poe.qpf_1_${fhr}

echo "cd ${DATA}; mkdir qpf_${fhr}_1; cd qpf_${fhr}_1 ; python ${HOMEhref}/scripts/make_easfracqpf_combo.py ${fhr} 1 > qpf_combo_${dom}_${cyc}_1h_${fhr}.log" >> poe.qpf_1_${fhr}

# echo "cd ${DATA}; mkdir snow_${fhr}_1; cd snow_${fhr}_1; python ${HOMEhref}/scripts/make_easfracsnow_combo.py ${fhr} 1 >  snow_combo_${dom}_${cyc}_1h_${fhr}.log" >> poe.qpf_1
chmod 775 poe.qpf_1_${fhr}
echo "./poe.qpf_1_${fhr} &" >> poe.qpf_1b

done

echo "wait" >> poe.qpf_1b
chmod 775 poe.qpf_1b


if [ ${dom}  =  "conus" ]
then
# export NODES=10
# aprun -j 1 -n 180 -N 18 -d 1 cfp poe.qpf
# export NODES=12
# aprun -j 1 -n 180 -N 15 -d 1 cfp poe.qpf

srun -n1 -N1 ./poe.qpf_3_03 &
srun -n1 -N1 ./poe.qpf_3_06 &
srun -n1 -N1 ./poe.qpf_3_09 &
srun -n1 -N1 ./poe.qpf_3_12 &
srun -n1 -N1 ./poe.qpf_3_15 &
srun -n1 -N1 ./poe.qpf_3_18 &
srun -n1 -N1 ./poe.qpf_3_21 &
srun -n1 -N1 ./poe.qpf_3_24 &
srun -n1 -N1 ./poe.qpf_3_27 &
srun -n1 -N1 ./poe.qpf_3_30 &
srun -n1 -N1 ./poe.qpf_3_33 &
srun -n1 -N1 ./poe.qpf_3_36 &
srun -n1 -N1 ./poe.qpf_3_39 &
srun -n1 -N1 ./poe.qpf_3_42 &
srun -n1 -N1 ./poe.qpf_3_45 &
srun -n1 -N1 ./poe.qpf_3_48 &
srun -n1 -N1 ./poe.qpf_3_51 &
srun -n1 -N1 ./poe.qpf_3_54 &
srun -n1 -N1 ./poe.qpf_3_57 &
srun -n1 -N1 ./poe.qpf_3_60 &
wait

echo DONE 3 hr


srun -n1 -N1 ./poe.qpf_1_01 &
srun -n1 -N1 ./poe.qpf_1_02 &
srun -n1 -N1 ./poe.qpf_1_03 &
srun -n1 -N1 ./poe.qpf_1_04 &
srun -n1 -N1 ./poe.qpf_1_05 &
srun -n1 -N1 ./poe.qpf_1_06 &
srun -n1 -N1 ./poe.qpf_1_07 &
srun -n1 -N1 ./poe.qpf_1_08 &
srun -n1 -N1 ./poe.qpf_1_09 &
srun -n1 -N1 ./poe.qpf_1_10 &
srun -n1 -N1 ./poe.qpf_1_11 &
srun -n1 -N1 ./poe.qpf_1_12 &
srun -n1 -N1 ./poe.qpf_1_13 &
srun -n1 -N1 ./poe.qpf_1_14 &
srun -n1 -N1 ./poe.qpf_1_15 &
srun -n1 -N1 ./poe.qpf_1_16 &
srun -n1 -N1 ./poe.qpf_1_17 &
srun -n1 -N1 ./poe.qpf_1_18 &
srun -n1 -N1 ./poe.qpf_1_19 &
srun -n1 -N1 ./poe.qpf_1_20 &
wait

srun -n1 -N1 ./poe.qpf_1_21 &
srun -n1 -N1 ./poe.qpf_1_22 &
srun -n1 -N1 ./poe.qpf_1_23 &
srun -n1 -N1 ./poe.qpf_1_24 &
srun -n1 -N1 ./poe.qpf_1_25 &
srun -n1 -N1 ./poe.qpf_1_26 &
srun -n1 -N1 ./poe.qpf_1_27 &
srun -n1 -N1 ./poe.qpf_1_28 &
srun -n1 -N1 ./poe.qpf_1_29 &
srun -n1 -N1 ./poe.qpf_1_30 &
srun -n1 -N1 ./poe.qpf_1_31 &
srun -n1 -N1 ./poe.qpf_1_32 &
srun -n1 -N1 ./poe.qpf_1_33 &
srun -n1 -N1 ./poe.qpf_1_34 &
srun -n1 -N1 ./poe.qpf_1_35 &
srun -n1 -N1 ./poe.qpf_1_36 &
srun -n1 -N1 ./poe.qpf_1_37 &
srun -n1 -N1 ./poe.qpf_1_38 &
srun -n1 -N1 ./poe.qpf_1_39 &
srun -n1 -N1 ./poe.qpf_1_40 &
wait

srun -n1 -N1 ./poe.qpf_1_41 &
srun -n1 -N1 ./poe.qpf_1_42 &
srun -n1 -N1 ./poe.qpf_1_43 &
srun -n1 -N1 ./poe.qpf_1_44 &
srun -n1 -N1 ./poe.qpf_1_45 &
srun -n1 -N1 ./poe.qpf_1_46 &
srun -n1 -N1 ./poe.qpf_1_47 &
srun -n1 -N1 ./poe.qpf_1_48 &
srun -n1 -N1 ./poe.qpf_1_49 &
srun -n1 -N1 ./poe.qpf_1_50 &
srun -n1 -N1 ./poe.qpf_1_51 &
srun -n1 -N1 ./poe.qpf_1_52 &
srun -n1 -N1 ./poe.qpf_1_53 &
srun -n1 -N1 ./poe.qpf_1_54 &
srun -n1 -N1 ./poe.qpf_1_55 &
srun -n1 -N1 ./poe.qpf_1_56 &
srun -n1 -N1 ./poe.qpf_1_57 &
srun -n1 -N1 ./poe.qpf_1_58 &
srun -n1 -N1 ./poe.qpf_1_59 &
srun -n1 -N1 ./poe.qpf_1_60 &
wait

srun -n1 -N1 ./poe.qpf_6_06 &
srun -n1 -N1 ./poe.qpf_6_09 &
srun -n1 -N1 ./poe.qpf_6_12 &
srun -n1 -N1 ./poe.qpf_6_15 &
srun -n1 -N1 ./poe.qpf_6_18 &
srun -n1 -N1 ./poe.qpf_6_21 &
srun -n1 -N1 ./poe.qpf_6_24 &
srun -n1 -N1 ./poe.qpf_6_27 &
srun -n1 -N1 ./poe.qpf_6_30 &
srun -n1 -N1 ./poe.qpf_6_33 &
srun -n1 -N1 ./poe.qpf_6_36 &
srun -n1 -N1 ./poe.qpf_6_39 &
srun -n1 -N1 ./poe.qpf_6_42 &
srun -n1 -N1 ./poe.qpf_6_45 &
srun -n1 -N1 ./poe.qpf_6_48 &
srun -n1 -N1 ./poe.qpf_6_51 &
srun -n1 -N1 ./poe.qpf_6_54 &
srun -n1 -N1 ./poe.qpf_6_57 &
srun -n1 -N1 ./poe.qpf_6_60 &
srun -n1 -N1 ./poe.qpf_12_12 &
srun -n1 -N1 ./poe.qpf_12_15 &
wait
echo DONE 6 hr

srun -n1 -N1 ./poe.qpf_12_18 &
srun -n1 -N1 ./poe.qpf_12_21 &
srun -n1 -N1 ./poe.qpf_12_24 &
srun -n1 -N1 ./poe.qpf_12_27 &
srun -n1 -N1 ./poe.qpf_12_30 &
srun -n1 -N1 ./poe.qpf_12_33 &
srun -n1 -N1 ./poe.qpf_12_36 &
srun -n1 -N1 ./poe.qpf_12_39 &
srun -n1 -N1 ./poe.qpf_12_42 &
srun -n1 -N1 ./poe.qpf_12_45 &
srun -n1 -N1 ./poe.qpf_12_48 &
srun -n1 -N1 ./poe.qpf_12_51 &
srun -n1 -N1 ./poe.qpf_12_54 &
srun -n1 -N1 ./poe.qpf_12_57 &
srun -n1 -N1 ./poe.qpf_12_60 &
srun -n1 -N1 ./poe.qpf_24_24 &
srun -n1 -N1 ./poe.qpf_24_27 &
srun -n1 -N1 ./poe.qpf_24_30 &
srun -n1 -N1 ./poe.qpf_24_33 &
srun -n1 -N1 ./poe.qpf_24_36 &
srun -n1 -N1 ./poe.qpf_24_39 &
srun -n1 -N1 ./poe.qpf_24_42 &
srun -n1 -N1 ./poe.qpf_24_45 &
srun -n1 -N1 ./poe.qpf_24_48 &
srun -n1 -N1 ./poe.qpf_24_51 &
srun -n1 -N1 ./poe.qpf_24_54 &
srun -n1 -N1 ./poe.qpf_24_57 &
srun -n1 -N1 ./poe.qpf_24_60 &
wait

echo DONE 12 and 24  hr

# ./poe.qpf_3 &
# ./poe.qpf_6 &
# wait

elif [ $dom = "ak" ]
then
export NODES=6
aprun -j 1 -n 90 -N 15 -d 1 cfp poe.qpf

elif [ $dom = "pr" -o $dom = "hi" ]
then
export NODES=4
aprun -j 1 -n 64 -N 16 -d 1 cfp poe.qpf

fi


export err=$?; err_chk


if [ $err -eq 0 ]
then

fhr=01

while [ $fhr -le 60 ]
do

if [ ! -e $DATA/rrfsce.t${cyc}z.${dom}.pqpf01_easfrac.f${fhr}.grib2 ]
then
msg="FATAL ERROR: missing $DATA/rrfsce.t${cyc}z.${dom}.pqpf01_easfrac.f${fhr}.grib2"

echo $msg

# err_exit $msg
fi

# if [ ! -e $DATA/rrfsce.t${cyc}z.${dom}.snow01_easfrac.f${fhr}.grib2 ]
# then
# msg="FATAL ERROR: missing $DATA/rrfsce.t${cyc}z.${dom}.snow01_easfrac.f${fhr}.grib2"
# err_exit $msg
# fi

cat $DATA/rrfsce.t${cyc}z.${dom}.pqpf01_easfrac.f${fhr}.grib2 > $DATA/rrfsce.t${cyc}z.${dom}.eas.f${fhr}.grib2
# cat $DATA/rrfsce.t${cyc}z.${dom}.snow01_easfrac.f${fhr}.grib2 >> $DATA/rrfsce.t${cyc}z.${dom}.eas.f${fhr}.grib2

if [ $((fhr%3)) -eq 0 ]
then

if [ ! -e $DATA/rrfsce.t${cyc}z.${dom}.pqpf03_easfrac.f${fhr}.grib2 ]
then
msg="FATAL ERROR: missing $DATA/rrfsce.t${cyc}z.${dom}.pqpf03_easfrac.f${fhr}.grib2"
echo $msg
# err_exit $msg
fi

# if [ ! -e $DATA/rrfsce.t${cyc}z.${dom}.snow03_easfrac.f${fhr}.grib2 ]
# then
# msg="FATAL ERROR: missing $DATA/rrfsce.t${cyc}z.${dom}.snow03_easfrac.f${fhr}.grib2"
# err_exit $msg
# fi

cat $DATA/rrfsce.t${cyc}z.${dom}.pqpf03_easfrac.f${fhr}.grib2 >> $DATA/rrfsce.t${cyc}z.${dom}.eas.f${fhr}.grib2
# cat $DATA/rrfsce.t${cyc}z.${dom}.snow03_easfrac.f${fhr}.grib2 >> $DATA/rrfsce.t${cyc}z.${dom}.eas.f${fhr}.grib2

fi

if [ $((fhr%3)) -eq 0 -a $fhr -ge 6 ]
then

if [ ! -e $DATA/rrfsce.t${cyc}z.${dom}.pqpf06_easfrac.f${fhr}.grib2 ]
then
msg="FATAL ERROR: missing $DATA/rrfsce.t${cyc}z.${dom}.pqpf06_easfrac.f${fhr}.grib2"
# err_exit $msg
echo $msg
fi

# if [ ! -e $DATA/rrfsce.t${cyc}z.${dom}.snow06_easfrac.f${fhr}.grib2 ]
# then
# msg="FATAL ERROR: missing $DATA/rrfsce.t${cyc}z.${dom}.snow06_easfrac.f${fhr}.grib2"
# err_exit $msg
# fi

cat $DATA/rrfsce.t${cyc}z.${dom}.pqpf06_easfrac.f${fhr}.grib2 >> $DATA/rrfsce.t${cyc}z.${dom}.eas.f${fhr}.grib2
# cat $DATA/rrfsce.t${cyc}z.${dom}.snow06_easfrac.f${fhr}.grib2 >> $DATA/rrfsce.t${cyc}z.${dom}.eas.f${fhr}.grib2

fi

if [ $((fhr%3)) -eq 0 -a $fhr -ge 12 ]
then

if [ ! -e $DATA/rrfsce.t${cyc}z.${dom}.pqpf12_easfrac.f${fhr}.grib2 ]
then
msg="FATAL ERROR: missing $DATA/rrfsce.t${cyc}z.${dom}.pqpf12_easfrac.f${fhr}.grib2"
# err_exit $msg
echo $msg
fi

cat $DATA/rrfsce.t${cyc}z.${dom}.pqpf12_easfrac.f${fhr}.grib2 >> $DATA/rrfsce.t${cyc}z.${dom}.eas.f${fhr}.grib2
fi

if [ $((fhr%3)) -eq 0 -a $fhr -ge 24 ]
then

if [ ! -e $DATA/rrfsce.t${cyc}z.${dom}.pqpf24_easfrac.f${fhr}.grib2 ]
then
msg="FATAL ERROR: missing $DATA/rrfsce.t${cyc}z.${dom}.pqpf24_easfrac.f${fhr}.grib2"
# err_exit $msg
echo $msg
fi

cat $DATA/rrfsce.t${cyc}z.${dom}.pqpf24_easfrac.f${fhr}.grib2 >> $DATA/rrfsce.t${cyc}z.${dom}.eas.f${fhr}.grib2
fi

if [ $SENDCOM == 'YES' ]
then
cp $DATA/rrfsce.t${cyc}z.${dom}.eas.f${fhr}.grib2 ${COMOUT}/ensprod/
## $WGRIB2 $DATA/rrfsce.t${cyc}z.${dom}.eas.f${fhr}.grib2 -match APCP -grib ${COMOUT}/ensprod/rrfsce.t${cyc}z.${dom}.easffair.f${fhr}.grib2
$WGRIB2 ${COMOUT}/ensprod/rrfsce.t${cyc}z.${dom}.eas.f${fhr}.grib2 -s > ${COMOUT}/ensprod/rrfsce.t${cyc}z.${dom}.eas.f${fhr}.grib2.idx
fi

let fhr=fhr+1

if [ $fhr -lt 10 ]
then
fhr=0${fhr}
fi

done

fi


########################################################

msg"JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

cd $DATAROOT
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date
